services:
   redis: 
     image: "redis:alpine"
     ports:
       - '6379:6379' 
   web:
     build: .
     environment:
       - PYTHONUNBUFFERED=1
     ports:
       - "5000:5000"
     volumes:
       - .:/code
     depends_on:
       - redis